version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: guillaumefalvet/task-management-app:1.0.0
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/database/init:/docker-entrypoint-initdb.d
volumes:
  pgdata: {}
