@port = {{$dotenv PORT}}
@host = {{$dotenv HOST}}
@protocol = {{$dotenv HTTP_PROTOCOL}}
@endpoint = {{protocol}}://{{host}}:{{port}}
@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}
@id = {{createTask.response.body.id}}

#### --------------AUTH--------------
### Create Account
POST {{ endpoint }}/api/auth/create-account
content-type: application/json

{
    "username": "http@gui.com",
    "password": "asAz89saas&!çç2)$"
}

### Login
# @name login
POST {{ endpoint }}/api/auth/login
content-type: application/json

{
    "username": "http@gui.com",
    "password": "asAz89saas&!çç2)$"
}

### Refresh Token
# @name login
POST {{endpoint}}/api/auth/refresh-token
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}

#### --------------TASKS--------------
### getAllTasks
GET {{ endpoint }}/api/tasks
Authorization: Bearer {{accessToken}}

### getAllTasksgetTasksWithFilters
GET {{ endpoint }}/api/tasks?status=IN_PROGRESS
Authorization: Bearer {{accessToken}}

### getTaskById
GET {{ endpoint }}/api/tasks/{{id}}
Authorization: Bearer {{accessToken}}

### createTask
# @name createTask
POST {{ endpoint }}/api/tasks
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}

title=Clean My Room&description=lots of stuff to do

### updateTask
PATCH {{ endpoint }}/api/tasks/{{{{id}}}}/status
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}

status=DONE


### deleteTask
DELETE  {{ endpoint }}/tasks/{{id}}
Authorization: Bearer {{accessToken}}