@endpoint = http://localhost:3000
@accessToken = {{login.response.body.accessToken}}

### getAllTasks
GET {{ endpoint }}/tasks
Authorization: Bearer {{accessToken}}


### getAllTasksgetTasksWithFilters
GET {{ endpoint }}/tasks?status=IN_PROGRESS
Authorization: Bearer {{accessToken}}

### getTaskById
GET {{ endpoint }}/tasks/40737541-1ca0-4197-929e-7e3273d5ba07
Authorization: Bearer {{accessToken}}

### createTask
POST {{ endpoint }}/tasks
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}

title=Clean My Room&description=lots of stuff to do

### updateTask
PATCH {{ endpoint }}/tasks/df4d5063-b61a-4270-8272-d06d3ee38e94/status
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{accessToken}}

status=DONE


### deleteTask
DELETE  {{ endpoint }}/tasks/df4d5063-b61a-4270-8272-d06d3ee38e94
Authorization: Bearer {{accessToken}}

### Sign In
# @name login
POST {{ endpoint }}/auth/signin
content-type: application/json

{
    "username": "gui@gui.com",
    "password": "asasasAz892)$"
}