@endpoint = http://localhost:3000
@accessToken = {{login.response.body.accessToken}}

### getAllTasks
GET {{ endpoint }}/tasks
Authorization: Bearer {{accessToken}}

### Sign Up
POST {{ endpoint }}/auth/signup
content-type: application/json

{
    "username": "gui@gui.com",
    "password": "asasasAz892)$"
}

### Sign In
# @name login
POST {{ endpoint }}/auth/signin
content-type: application/json

{
    "username": "gui@gui.com",
    "password": "asasasAz892)$"
}
