export enum DatabaseTypeEnum {
  MySQL = 'mysql',
  Postgres = 'postgres',
  CockroachDB = 'cockroachdb',
  SAP = 'sap',
  MariaDB = 'mariadb',
  SQLite = 'sqlite',
  Cordova = 'cordova',
  ReactNative = 'react-native',
  NativeScript = 'nativescript',
  SQLJS = 'sqljs',
  Oracle = 'oracle',
  MSSQL = 'mssql',
  MongoDB = 'mongodb',
  AuroraMySQL = 'aurora-mysql',
  AuroraPostgres = 'aurora-postgres',
  Expo = 'expo',
  BetterSQLite3 = 'better-sqlite3',
  Capacitor = 'capacitor',
  Spanner = 'spanner',
}
